nile:
  schema-service:
    enabled: true
    database: mongodb
    subtype: import
  notification-service:
    enabled: true
    topic: notifications
    source: Ingestion
  mainlog-producer:
    enabled: true
  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      groupId: nile-ingestion-local
      enabled: true
    producer:
      enabled: true
    mainlog-topic: mainlog
    ingestion-topic: ingestion
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/nile
      database: nile

