package com.sourcesense.nile.core.enumeration;

public enum NotificationEvent {

    SEND_RAW_DATA_SUCCESS,
    SEND_RAW_DATA_FAILED,

    IMPORT_SCHEMA_REVERSE_CREATED,

    MAINLOG_PUBLISH_SUCCESS,
    MAINLOG_PUBLISH_FAILED,
    SCHEMA_PUBLISH_SUCCESS,
    SCHEMA_PUBLISH_FAILED
}
