package com.sourcesense.nile.core.enumeration;

public enum NotificationEvent {

    SEND_RAW_DATA_SUCCESS,
    SEND_RAW_DATA_FAILED,

    IMPORT_SCHEMA_REVERSE_CREATED,

    INGESTION_SUCCEDED,
    INGESTION_FAILED,
    SCHEMA_PUBLISHED,
    SCHEMA_PUBLISH_FAILED,

    EXTRACT_CSV_ROW_FAILED,
    READ_CSV_HEADER_FAILED,
    READ_CSV_ROW_FAILED
}
