sources:
  - name: Mongoose
    handler:
      mongoose:
        connectionString: mongodb://localhost:27017/ingestion
        models:
          - name: users
            path: ./src/db/graphql/models.js#users
          - name: news
            path: ./src/db/graphql/models.js#news

serve:
  exampleQuery: ./assets/queries/*.graphql
  browser: false
  endpoint: /query
