version: "2"

services:
  mongodb-rest:
    build: ./
    environment:
      - MONGO_URI=mongodb://my_user:password123@mongodb:27017/my_database
      - SCHEMAS_SOURCE=/assets/schemas.json
    ports:
      - "6650:6650"
    volumes:
      - ./assets/:/assets/
    image: sourcesense/joyce-rest:latest
