version: "2"

services:
  # mongodb:
  #   image: "bitnami/mongodb:latest"
  #   environment:
  #     - MONGODB_USERNAME=my_user
  #     - MONGODB_PASSWORD=password123
  #     - MONGODB_DATABASE=my_database
  #   ports:
  #     - "27017:27017"
  myapp:
    build: ./
    environment:
      - MONGO_URI=mongodb://my_user:password123@mongodb:27017/my_database
      - SCHEMAS_SOURCE=/assets/schemas.json
    ports:
      - "3000:3000"
    volumes:
      - ./assets/:/assets/
    # depends_on:
    #   - "mongodb"
    image: registry.sourcesense.com/nile/api-rest:latest
