spring:
  main:
    web-application-type: none
joyce:
  kafka:
    content-topic: joyce_content
    schema-topic: joyce_schema
    bootstrapAddress: kafka:9092
    producer:
      enabled: true
    consumer:
      groupId: joyce-mongodb-projector-local
      enabled: true
  notification-service:
    enabled: true
    source: MongodbSink
    topic: joyce_notification
  schema-service:
    enabled: false
    database: mongodb
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/joyce
      database: joyce
      metadata-indexes:
        - raw_uri: 1
        - schema_uid: 1
        - schema_name: 1
