spring:
  profiles:
    active:
      - mongodb
nile:
  kafka:
    mainlog-topic: mainlog
    bootstrapAddress: kafka:9092
    consumer:
      groupId: nile-mongodb-projector-local
      enabled: true
  projection:
    headers:
      uid: X-Nile-uid
      collection: X-Nile-collection
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/ingestion
      database: ingestion