spring:
  main:
    web-application-type: none
  profiles:
    active:
      - mongodb
nile:
  kafka:
    mainlog-topic: mainlog
    bootstrapAddress: kafka:9092
    consumer:
      groupId: nile-mongodb-projector-local
      enabled: true
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/ingestion
      database: ingestion