server:
  port: 6651
opentracing:
  jaeger:
    service-name: import-gateway
    udp-sender:
      host: localhost
      port:  6831
springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true

joyce:
  schema-transformer-plugin:
    enabled: true
    jar-path: /app/custom-handlers
  schema-service:
    enabled: true
    database: mongodb
    subtype: import
  notification-service:
    enabled: true
    topic: joyce_notification
    source: ImportGateway
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/joyce
      database: joyce
  content-producer:
    enabled: true
  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      groupId: joyce-import-consumer-local
      enabled: true
    producer:
      enabled: true
    import:
      topic: joyce_import
    content:
      topic: joyce_content
      cleanup: compact
    notification:
      topic: joyce_notification
      retention: 86400000

