server:
  port: 6651

springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
joyce:
  schema-service:
    enabled: true
    database: kafka
    subtype: import
  notification-service:
    enabled: true
    topic: joyce_notification
    source: ImportGateway
  content-producer:
    enabled: true
  ksql:
    host: localhost
    port: 8088
  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      groupId: joyce-import-consumer-local
      enabled: true
    producer:
      enabled: true
    import-topic: joyce_import
    content-topic: joyce_content

