version: "3.6"

services:
  mongodb:
    image: "bitnami/mongodb:4.4.5"
    environment:
      - MONGODB_ROOT_PASSWORD=toor
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=joyce
    ports:
      - "27017:27017"
  joyce-api:
    build: ./
    environment:
      - JOYCE_API_MONGO_URI=mongodb://user:password@mongodb:27017/joyce
      - JOYCE_API_WORKDIR=/usr/joyce/workdir
      - JOYCE_API_CONFIG_SOURCE=/opt/config.json
      - JOYCE_API_SCHEMA_GRPC_ENDPOINT=172.16.6.2:30244
    ports:
      - "6650:6650"
    volumes:
      - ./config.json:/opt/config.json
      - ./data:/usr/joyce/workdir
    depends_on:
      - mongodb
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268"
      - "14250"
