name: 'Docker build and publish'
description: 'Build docker container and publish to Sourcesense docker hub'
inputs:
  module:
    description: 'module to build and publish'
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build and Push Docker image
      run: |
        docker build . -t sourcesense/${{inputs.module}}:${{steps.vars.outputs.VERSION}}
        docker push sourcesense/${{inputs.module}}:${{steps.vars.outputs.VERSION}}
        docker tag sourcesense/${{inputs.module}}:${{steps.vars.outputs.VERSION}} sourcesense/${{inputs.module}}:latest
        docker push sourcesense/${{inputs.module}}:latest
      working-directory: ${{inputs.module}}
