name: 'Docker build and publish'
description: 'Build docker container and publish to Sourcesense docker hub'
inputs:
  module:
    description: 'module to build and publish'
    required: true
  version:
    required: true
  docker_user:
    required: true
    default: sourcesense
  docker_pwd:
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker login
      run: echo ${{ inputs.docker_pwd }} | docker login -u ${{ inputs.docker_user }} --password-stdin
    - name: Build and Push Docker image
      run: |
        docker build . -t sourcesense/${{inputs.module}}:${{inputs.version}}
        docker push sourcesense/${{inputs.module}}:${{inputs.version}}
        docker tag sourcesense/${{inputs.module}}:${{inputs.version}} sourcesense/${{inputs.module}}:latest
        docker push sourcesense/${{inputs.module}}:latest
      working-directory: ${{inputs.module}}
