server:
  port: 6651

springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
nile:
  schema-service:
    enabled: true
    database: kafka
    subtype: import
  notification-service:
    enabled: true
    topic: notifications
    source: ImportGateway
  mainlog-producer:
    enabled: true
  ksql:
    host: localhost
    port: 8088
  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      groupId: nile-import-consumer-local
      enabled: true
    producer:
      enabled: true
    mainlog-topic: mainlog
    import-topic: import

