nile:
  schema-service:
    enabled: true
    database: mongodb
    uidPattern: nile://ingestion/schema/%s
  notification-service:
    enabled: true
    topic: notifications
    source: Ingestion
  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      groupId: nile-ingestion-local
      enabled: true
    producer:
      enabled: true
    mainlog-topic: mainlog
    ingestion-topic: ingestion
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/ingestion
      database: ingestion

