nile:
  schema-service:
    enabled: true
    uidPattern: nile://ingestion/schema/%s
  notification-service:
    enabled: true
  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      groupId: nile-ingestion-local
      enabled: true
    producer:
      enabled: true
    mainlog-topic: mainlog
    ingestion-topic: ingestion

