nile:
  schema-service:
    enabled: true
    uidPattern: nile://ingestion/schema/%s
  ingestion:
    kafka:
      mainlog-topic: mainlog
      ingestion-topic: ingestion
      bootstrapAddress: kafka:9092
