name: Kafka Connect Docker Release

on:
  push:
    tags:
      - "connect-*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-java
      - name: Build
        run: mvn -f InsertJoyceMessageKey/pom.xml clean package
        working-directory: ./joyce-kafka-connect
      - name: Set VERSION
        id: vars
        run: |
          echo "::set-output name=VERSION::$(echo ${GITHUB_REF#refs/tags/connect-})"
          echo "VERSION=${{steps.vars.outputs.VERSION}}"
      - uses: ./.github/actions/docker-publish
        with:
          module: joyce-kafka-connect
          tag: ${{ steps.vars.outputs.VERSION }}
          docker_pwd: ${{ secrets.DOCKER_PASSWORD }}
