name: Build Release

on:
  push:
    tags:
      - "sink-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: ./.github/actions/prepare-java
      - name: Set VERSION
        id: vars
        run: |
          echo "::set-output name=VERSION::$(echo ${GITHUB_REF:10})"
          echo "VERSION=${{steps.vars.outputs.VERSION}}"
      - name: Build
        run: mvn --batch-mode --update-snapshots -Drevision=${{steps.vars.outputs.VERSION}} verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: ./.github/actions/docker-publish
        with:
          module: joyce-mongodb-sink
          tag: steps.vars.outputs.VERSION
          docker_pwd: secrets.DOCKER_PASSWORD
