name: Publish Libraries

on:
  push:
    tags:
      - "libs-*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-java
      - name: Set VERSION
        id: vars
        run: |
          echo "::set-output name=VERSION::$(echo ${GITHUB_REF#parent-})"
          echo "VERSION=${{steps.vars.outputs.VERSION}}"
      - name: Publish package
        run: mvn --batch-mode -Drevision=${{steps.vars.outputs.VERSION}} deploy sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
