name: Publish Release

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set VERSION 
        id: vars
        run: |
          echo "::set-output name=VERSION::$(echo ${GITHUB_REF:10})"
          echo "VERSION=${{steps.vars.outputs.VERSION}}"
      - name: Publish package
        run: mvn --batch-mode -Drevision=${{steps.vars.outputs.VERSION}} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
