name: Build Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set VERSION
        id: vars
        run: |
          echo "::set-output name=VERSION::$(echo ${GITHUB_REF:10})"
          echo "VERSION=${{steps.vars.outputs.VERSION}}"
      - name: Build
        run: mvn --batch-mode --update-snapshots -Drevision=${{steps.vars.outputs.VERSION}} verify
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push Docker image
        run: |
          docker build . -t sourcesense/joyce-import-gateway:${{steps.vars.outputs.VERSION}}
          docker push sourcesense/joyce-import-gateway:${{steps.vars.outputs.VERSION}}
          docker tag sourcesense/joyce-import-gateway:${{steps.vars.outputs.VERSION}} sourcesense/joyce-import-gateway:latest
          docker push sourcesense/joyce-import-gateway:latest
