name: Build Release

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION
        id: vars
        run: |
          echo "::set-output name=VERSION::$(echo ${GITHUB_REF:10})"
          echo "VERSION=${{steps.vars.outputs.VERSION}}"
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push Docker image
        run: |
          docker build . -t sourcesense/joyce-rest:${{steps.vars.outputs.VERSION}} 
          docker push sourcesense/joyce-rest:${{steps.vars.outputs.VERSION}}
          docker tag sourcesense/joyce-rest:${{steps.vars.outputs.VERSION}} sourcesense/joyce-rest:latest
          docker push sourcesense/joyce-rest:latest
